on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

name: SonarQube Scan
jobs:
  build:
    name: build project
    runs-on: ubuntu-latest
    steps:
      - name: checking out
        uses: actions/checkout@master
        with:
          arguments: build
  sonarqube:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@master
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@v1.2.0
        with:
          host: https://sonar.anywhere.co
          login: 779f0a933f16fd75121fc5a405d66a24f7a2412a